config:
  WOLF:
    weight: 50
    speed: 3
    saturation: 8
    count: 30
  SNAKE:
    weight: 2
    speed: 1
    saturation: 0.3
    count: 123
  FOX:
    weight: 4
    speed: 3
    saturation: 1
    count: 50
  BEAR:
    weight: 250
    speed: 2
    saturation: 38
    count: 7
  EAGLE:
    weight: 6
    speed: 4
    saturation: 1
    count: 166
  HORSE:
    weight: 300
    speed: 3
    saturation: 45
    count: 23
  DEER:
    weight: 170
    speed: 3
    saturation: 26
    count: 41
  RABBIT:
    weight: 3
    speed: 3
    saturation: 0.45
    count: 750
  GOAT:
    weight: 65
    speed: 1
    saturation: 10
    count: 107
  BOAR:
    weight: 65
    speed: 1
    saturation: 10
    count: 107
  MOUSE:
    weight: 65
    speed: 1
    saturation: 10
    count: 107
  SHEEP:
    weight: 45
    speed: 1
    saturation: 7
    count: 156
  BUFFALO:
    weight: 350
    speed: 1
    saturation: 53
    count: 20
  DUCK:
    weight: 1
    speed: 1
    saturation: 0.15
    count: 500
  CATERPILLAR:
    weight: 0.01
    speed: 1
    saturation: 0.0025
    count: 1000
  PLANT:
    weight: 1
    speed:
    saturation:
    count: 1000
